Repository AY1920S1-CS2103T-F12-3/main, pull requests merged in 2019-11, with the labels that each got.

#165 Update user guide to include user-friendliness features
  docs/UserGuide.adoc
  docs/images/ug_autocomplete1.png
  docs/images/ug_autocomplete2.png
  docs/images/ug_autocomplete3.png
  docs/images/ug_prompt1.png
  docs/images/ug_prompt2.png
  docs/images/ug_prompt3.png
Labels: type.Task

#237 Update PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/shiweing.adoc
Labels: type.Documentation

#227 Resolve some UG issues
  docs/UserGuide.adoc
Labels: type.Documentation

#242 Update contact show
  src/main/java/tagline/logic/commands/contact/ShowContactCommand.java
  src/main/java/tagline/model/Model.java
  src/main/java/tagline/model/ModelManager.java
  src/main/java/tagline/model/group/Group.java
  src/main/java/tagline/model/group/GroupBook.java
  src/main/java/tagline/model/group/GroupManager.java
  src/main/java/tagline/model/group/GroupModel.java
  src/main/java/tagline/model/group/MemberId.java
  src/main/java/tagline/model/group/UniqueGroupList.java
  src/test/java/tagline/logic/commands/contact/CreateContactCommandTest.java
  src/test/java/tagline/logic/commands/group/CreateGroupCommandTest.java
  src/test/java/tagline/logic/commands/note/CreateNoteCommandTest.java
Labels: type.Enhancement

#238 UG and PPP Update
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/frontpage.png
  docs/team/e0031374.adoc
  docs/team/e0031374.pdf
  docs/team/tanlk99.pdf
  src/main/java/tagline/model/util/SampleDataUtil.java
Labels: type.Documentation
