Repository AY1920S1-CS2103T-F12-3/main, pull requests merged in 2019-10, with the labels that each got.

#37 Fix typos in Developer Guide and User Guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: documentation

#9 Add chat pane to GUI
  src/main/java/tagline/ui/ChatPane.java
  src/main/java/tagline/ui/DialogBox.java
  src/main/java/tagline/ui/MainWindow.java
  src/main/java/tagline/ui/ResultDisplay.java
  src/main/resources/images/tagline_icon.png
  src/main/resources/view/ChatPane.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DialogBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: enhancement

#46 Implement view switching in GUI
  src/main/java/tagline/logic/commands/CommandResult.java
  src/main/java/tagline/ui/ContactResultView.java
  src/main/java/tagline/ui/DummyResultView.java
  src/main/java/tagline/ui/MainWindow.java
  src/main/java/tagline/ui/ResultView.java
  src/main/resources/view/ContactResultView.fxml
  src/main/resources/view/DummyResultView.fxml
  src/test/java/tagline/logic/commands/CommandResultTest.java
Labels: type.Enhancement

#62 Update contact parser
  docs/UserGuide.adoc
  src/main/java/tagline/logic/commands/contact/ClearContactCommand.java
  src/main/java/tagline/logic/commands/contact/CreateContactCommand.java
  src/main/java/tagline/logic/commands/contact/DeleteContactCommand.java
  src/main/java/tagline/logic/commands/contact/EditContactCommand.java
  src/main/java/tagline/logic/commands/contact/FindContactCommand.java
  src/main/java/tagline/logic/parser/contact/AddContactParser.java
  src/main/java/tagline/logic/parser/contact/ContactCommandParser.java
  src/test/java/tagline/logic/LogicManagerTest.java
  src/test/java/tagline/logic/commands/CreateContactCommandIntegrationTest.java
  src/test/java/tagline/logic/commands/CreateContactCommandTest.java
  src/test/java/tagline/logic/parser/AddContactParserTest.java
  src/test/java/tagline/logic/parser/ContactCommandParserTest.java
  src/test/java/tagline/testutil/PersonUtil.java
Labels: type.Task

#67 Add GUI tests with TestFX
  .travis.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/tagline/commons/core/GuiSettings.java
  src/main/java/tagline/ui/MainWindow.java
  src/main/java/tagline/ui/UiManager.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/ContactResultView.fxml
  src/main/resources/view/DummyResultView.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/tagline/testutil/CommandResultBuilder.java
  src/test/java/tagline/testutil/LogicStub.java
  src/test/java/tagline/ui/ChatPaneTest.java
  src/test/java/tagline/ui/ResultPaneTest.java
Labels: type.Task

#76 Fix buggy interface in headed GUI test
  src/test/java/tagline/ui/ChatPaneTest.java
  src/test/java/tagline/ui/ResultPaneTest.java
Labels: type.Bug

#78 Create view to display notes
  src/main/java/tagline/MainApp.java
  src/main/java/tagline/logic/commands/CommandResult.java
  src/main/java/tagline/model/note/NoteIdCounter.java
  src/main/java/tagline/model/note/NoteModelManager.java
  src/main/java/tagline/model/util/SampleDataUtil.java
  src/main/java/tagline/ui/ContactListCard.java
  src/main/java/tagline/ui/ContactListPanel.java
  src/main/java/tagline/ui/MainWindow.java
  src/main/java/tagline/ui/NoteListCard.java
  src/main/java/tagline/ui/NoteListPanel.java
  src/main/java/tagline/ui/NoteResultView.java
  src/main/resources/view/ContactListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/NoteListCard.fxml
  src/main/resources/view/NoteListPanel.fxml
  src/main/resources/view/NoteResultView.fxml
  src/test/data/JsonNoteBookStorageTest/invalidAndValidNoteNoteBook.json
  src/test/data/JsonSerializableNoteBookTest/invalidNoteNoteBook.json
  src/test/java/tagline/logic/commands/note/CreateNoteCommandTest.java
  src/test/java/tagline/model/note/ContentContainsKeywordsPredicateTest.java
  src/test/java/tagline/storage/JsonAdaptedNoteTest.java
  src/test/java/tagline/storage/JsonNoteBookStorageTest.java
  src/test/java/tagline/storage/JsonSerializableNoteBookTest.java
  src/test/java/tagline/testutil/NoteBuilder.java
  src/test/java/tagline/ui/ResultPaneTest.java
Labels: status.Ongoing, type.Task

#72 Implement tag manager
  src/main/java/tagline/logic/parser/contact/ContactParserUtil.java
  src/main/java/tagline/logic/parser/contact/EditCommandParser.java
  src/main/java/tagline/model/ReadOnlyTagList.java
  src/main/java/tagline/model/contact/AddressBook.java
  src/main/java/tagline/model/contact/ContactId.java
  src/main/java/tagline/model/contact/ContactManager.java
  src/main/java/tagline/model/contact/ContactModel.java
  src/main/java/tagline/model/contact/ReadOnlyAddressBook.java
  src/main/java/tagline/model/contact/UniqueContactList.java
  src/main/java/tagline/model/note/Title.java
  src/main/java/tagline/model/tag/Tag.java
  src/main/java/tagline/model/tag/TagList.java
  src/main/java/tagline/model/tag/TagManager.java
  src/main/java/tagline/model/tag/TagModel.java
  src/main/java/tagline/model/tag/exceptions/DuplicateTagException.java
  src/main/java/tagline/storage/JsonAdaptedContact.java
  src/main/java/tagline/storage/JsonAdaptedTag.java
  src/test/java/tagline/logic/parser/ContactParserUtilTest.java
  src/test/java/tagline/storage/JsonAdaptedNoteTest.java
Labels: status.Ongoing

#83 Integrate GUI, Contact, Note and Storage components
  .gitignore
  src/main/java/tagline/MainApp.java
  src/main/java/tagline/logic/Logic.java
  src/main/java/tagline/logic/LogicManager.java
  src/main/java/tagline/logic/commands/CommandResult.java
  src/main/java/tagline/logic/commands/contact/ClearContactCommand.java
  src/main/java/tagline/logic/commands/contact/CreateContactCommand.java
  src/main/java/tagline/logic/commands/contact/DeleteContactCommand.java
  src/main/java/tagline/logic/commands/contact/EditContactCommand.java
  src/main/java/tagline/logic/commands/contact/FindContactCommand.java
  src/main/java/tagline/logic/commands/contact/ListContactCommand.java
  src/main/java/tagline/logic/commands/note/CreateNoteCommand.java
  src/main/java/tagline/model/Model.java
  src/main/java/tagline/model/ModelManager.java
  src/main/java/tagline/model/ReadOnlyUserPrefs.java
  src/main/java/tagline/model/UserPrefs.java
  src/main/java/tagline/model/note/NoteManager.java
  src/main/java/tagline/model/util/SampleDataUtil.java
  src/main/java/tagline/storage/Storage.java
  src/main/java/tagline/storage/StorageManager.java
  src/main/java/tagline/ui/ContactListCard.java
  src/main/java/tagline/ui/DummyResultView.java
  src/main/java/tagline/ui/MainWindow.java
  src/main/resources/view/ContactListCard.fxml
  src/main/resources/view/DummyResultView.fxml
  src/test/java/tagline/logic/LogicManagerTest.java
  src/test/java/tagline/logic/commands/ClearContactCommandTest.java
  src/test/java/tagline/logic/commands/CommandTestUtil.java
  src/test/java/tagline/logic/commands/CreateContactCommandIntegrationTest.java
  src/test/java/tagline/logic/commands/CreateContactCommandTest.java
  src/test/java/tagline/logic/commands/DeleteContactCommandTest.java
  src/test/java/tagline/logic/commands/EditContactCommandTest.java
  src/test/java/tagline/logic/commands/ExitCommandTest.java
  src/test/java/tagline/logic/commands/FindContactCommandTest.java
  src/test/java/tagline/logic/commands/HelpCommandTest.java
  src/test/java/tagline/logic/commands/ListContactCommandTest.java
  src/test/java/tagline/logic/commands/note/CreateNoteCommandTest.java
  src/test/java/tagline/model/ModelManagerTest.java
  src/test/java/tagline/model/note/NoteManagerTest.java
  src/test/java/tagline/storage/StorageManagerTest.java
  src/test/java/tagline/testutil/LogicStub.java
  src/test/java/tagline/ui/ChatPaneTest.java
  src/test/java/tagline/ui/ResultPaneTest.java
Labels: priority.High, type.Task

#86 Fix ContactListCard
  src/main/java/tagline/ui/ContactListCard.java
  src/main/resources/view/ContactListCard.fxml
Labels: priority.High, type.Bug

#101 Fix Broken Startup
  src/main/java/tagline/MainApp.java
  src/main/java/tagline/model/util/SampleDataUtil.java
Labels: severity.High, type.Bug

#108 Update architecture diagrams, UI structure, user stories, use cases and NFRs
  docs/DeveloperGuide.adoc
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Task

#114 Include User Prompt feature in DG
  docs/DeveloperGuide.adoc
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/UiChatPaneClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UiResultPaneClassDiagram.png
  docs/images/UserPromptSequenceDiagramStep1.png
  docs/images/UserPromptSequenceDiagramStep2.png
  docs/images/UserPromptSequenceDiagramStep3.png
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
Labels: type.Task

#103 Refactor ResultPane into a separate class
  src/main/java/tagline/ui/ContactListCard.java
  src/main/java/tagline/ui/ContactListPanel.java
  src/main/java/tagline/ui/MainWindow.java
  src/main/java/tagline/ui/NoteListCard.java
  src/main/java/tagline/ui/ResultPane.java
  src/main/java/tagline/ui/ResultView.java
  src/main/resources/view/ContactListCard.fxml
  src/main/resources/view/ResultPane.fxml
  src/test/java/tagline/testutil/TypicalContacts.java
  src/test/java/tagline/testutil/TypicalNotes.java
  src/test/java/tagline/ui/ChatPaneTest.java
  src/test/java/tagline/ui/ContactListCardTest.java
  src/test/java/tagline/ui/NoteListCardTest.java
  src/test/java/tagline/ui/ResultPaneTest.java
Labels: type.Task

#136 Added some XML for Dev Guide
  README.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/drawioxml/ArchitectureDiagram.xml
  docs/diagrams/drawioxml/ArchitectureSequenceDiagram.xml
  docs/diagrams/drawioxml/ContactCreateSequenceDiagram.xml
  docs/diagrams/drawioxml/ContactLogicClassDiagram.xml
  docs/diagrams/drawioxml/ContactModelClassDiagram.xml
  docs/diagrams/drawioxml/ContactStorageClassDiagram.xml
  docs/diagrams/drawioxml/FilterKeywordSequenceDiagram1.xml
  docs/diagrams/drawioxml/FilterKeywordSequenceDiagram2.xml
  docs/diagrams/drawioxml/FilterTagSequenceDiagram.xml
  docs/diagrams/drawioxml/GroupContactsState0.xml
  docs/diagrams/drawioxml/GroupContactsState1.xml
  docs/diagrams/drawioxml/GroupContactsState2.xml
  docs/diagrams/drawioxml/GroupContactsState3.xml
  docs/diagrams/drawioxml/GroupContactsState4.xml
  docs/diagrams/drawioxml/LogicClassDiagram.xml
  docs/diagrams/drawioxml/ModelClassDiagram.xml
  docs/diagrams/drawioxml/NoteDeleteSequenceDiagram.xml
  docs/diagrams/drawioxml/NoteLogicClassDiagram.xml
  docs/diagrams/drawioxml/NoteModelClassDiagram.xml
  docs/diagrams/drawioxml/NoteStorageClassDiagram.xml
  docs/diagrams/drawioxml/StorageClassDiagram.xml
  docs/diagrams/drawioxml/UiChatPaneClassDiagram.xml
  docs/diagrams/drawioxml/UiClassDiagram.xml
  docs/diagrams/drawioxml/UiResultPaneClassDiagram.xml
  docs/diagrams/drawioxml/UserPromptSequenceDiagramStep1.xml
  docs/diagrams/drawioxml/UserPromptSequenceDiagramStep2.xml
  docs/diagrams/drawioxml/UserPromptSequenceDiagramStep3.xml
  docs/images/GroupContactsState1.png
  docs/images/StorageArchitectureDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.Task

#125 Implement Autocomplete feature
  README.adoc
  build.gradle
  src/main/java/tagline/ui/CommandBox.java
  src/main/java/tagline/ui/util/AutoCompleteNode.java
  src/main/java/tagline/ui/util/AutoCompleteUtil.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/tagline/ui/ChatPaneTest.java
  src/test/java/tagline/ui/ResultPaneTest.java
  src/test/java/tagline/ui/util/AutoCompleteNodeTest.java
Labels: type.Enhancement, type.Story

#141 Update tag storage and contact tag
  src/main/java/tagline/MainApp.java
  src/main/java/tagline/logic/commands/group/GroupCommand.java
  src/main/java/tagline/model/ReadOnlyUserPrefs.java
  src/main/java/tagline/model/UserPrefs.java
  src/main/java/tagline/model/contact/ContactId.java
  src/main/java/tagline/model/contact/ContactManager.java
  src/main/java/tagline/model/group/ContactIdEqualsSearchIdsPredicate.java
  src/main/java/tagline/model/tag/ContactTag.java
  src/main/java/tagline/model/tag/Tag.java
  src/main/java/tagline/model/tag/TagBook.java
  src/main/java/tagline/model/tag/TagId.java
  src/main/java/tagline/model/tag/TagIdGenerator.java
  src/main/java/tagline/model/tag/TagType.java
  src/main/java/tagline/model/tag/UniqueTagList.java
  src/main/java/tagline/storage/Storage.java
  src/main/java/tagline/storage/StorageManager.java
  src/main/java/tagline/storage/note/JsonAdaptedNote.java
  src/main/java/tagline/storage/tag/JsonAdaptedContactTag.java
  src/main/java/tagline/storage/tag/JsonAdaptedTag.java
  src/main/java/tagline/storage/tag/JsonSerializableTagBook.java
  src/main/java/tagline/storage/tag/JsonTagBookStorage.java
  src/test/java/tagline/logic/LogicManagerTest.java
  src/test/java/tagline/logic/commands/EditContactCommandTest.java
  src/test/java/tagline/logic/parser/TagParserUtilTest.java
  src/test/java/tagline/model/contact/AddressBookTest.java
  src/test/java/tagline/model/contact/ContactBuilder.java
  src/test/java/tagline/storage/JsonAdaptedNoteTest.java
  src/test/java/tagline/storage/StorageManagerTest.java
Labels: type.Task

#143 Fix truncated text in single group result view
  src/main/java/tagline/ui/GroupSingleResultView.java
  src/main/resources/view/GroupSingleResultView.fxml
Labels: severity.Low, type.Bug

#146 Add group tag
  src/main/java/tagline/logic/parser/tag/TagParserUtil.java
  src/main/java/tagline/model/tag/GroupTag.java
  src/main/java/tagline/storage/tag/JsonAdaptedGroupTag.java
  src/main/java/tagline/storage/tag/JsonSerializableTagBook.java
  src/test/java/tagline/logic/parser/TagParserUtilTest.java
Labels: type.Story, type.Task

#155 Add contact show command
  src/main/java/tagline/logic/commands/CommandResult.java
  src/main/java/tagline/logic/commands/contact/ClearContactCommand.java
  src/main/java/tagline/logic/commands/contact/CreateContactCommand.java
  src/main/java/tagline/logic/commands/contact/DeleteContactCommand.java
  src/main/java/tagline/logic/commands/contact/EditContactCommand.java
  src/main/java/tagline/logic/commands/contact/FindContactCommand.java
  src/main/java/tagline/logic/commands/contact/ListContactCommand.java
  src/main/java/tagline/logic/commands/contact/ShowContactCommand.java
  src/main/java/tagline/logic/commands/group/AddMemberToGroupCommand.java
  src/main/java/tagline/logic/commands/group/CreateGroupCommand.java
  src/main/java/tagline/logic/commands/group/FindGroupCommand.java
  src/main/java/tagline/logic/commands/group/RemoveMemberFromGroupCommand.java
  src/main/java/tagline/logic/parser/contact/ContactCommandParser.java
  src/main/java/tagline/logic/parser/contact/ShowContactParser.java
  src/main/java/tagline/model/contact/ContactIdEqualsSearchIdPredicate.java
  src/main/java/tagline/model/group/Group.java
  src/main/java/tagline/ui/ResultPane.java
  src/main/java/tagline/ui/contact/ContactListCard.java
  src/main/java/tagline/ui/contact/ContactListPanel.java
  src/main/java/tagline/ui/contact/ContactListResultView.java
  src/main/java/tagline/ui/contact/ContactProfileResultView.java
  src/main/java/tagline/ui/group/GroupListCard.java
  src/main/java/tagline/ui/group/GroupListPanel.java
  src/main/java/tagline/ui/group/GroupListResultView.java
  src/main/java/tagline/ui/group/GroupProfileResultView.java
  src/main/java/tagline/ui/note/NoteListCard.java
  src/main/java/tagline/ui/note/NoteListPanel.java
  src/main/java/tagline/ui/note/NoteListResultView.java
  src/main/java/tagline/ui/tag/TagListCard.java
  src/main/java/tagline/ui/tag/TagListPanel.java
  src/main/java/tagline/ui/tag/TagListResultView.java
  src/main/java/tagline/ui/util/AutoCompleteUtil.java
  src/main/resources/view/ContactListResultView.fxml
  src/main/resources/view/ContactProfileResultView.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/GroupListResultView.fxml
  src/main/resources/view/GroupProfileResultView.fxml
  src/main/resources/view/NoteListCard.fxml
  src/main/resources/view/NoteListResultView.fxml
  src/test/java/tagline/logic/commands/CommandResultTest.java
  src/test/java/tagline/logic/commands/contact/ClearContactCommandTest.java
  src/test/java/tagline/logic/commands/contact/CreateContactCommandIntegrationTest.java
  src/test/java/tagline/logic/commands/contact/DeleteContactCommandTest.java
  src/test/java/tagline/logic/commands/contact/EditContactCommandTest.java
  src/test/java/tagline/logic/commands/contact/FindContactCommandTest.java
  src/test/java/tagline/logic/commands/contact/ListContactCommandTest.java
  src/test/java/tagline/logic/commands/group/AddMemberToGroupCommandTest.java
  src/test/java/tagline/logic/commands/group/FindGroupCommandTest.java
  src/test/java/tagline/logic/commands/group/RemoveMemberFromGroupCommandTest.java
  src/test/java/tagline/ui/ContactListCardTest.java
  src/test/java/tagline/ui/GroupListCardTest.java
  src/test/java/tagline/ui/NoteListCardTest.java
  src/test/java/tagline/ui/ResultPaneTest.java
Labels: type.Story, type.Task

#150 Add user prompting feature
  src/main/java/tagline/logic/Logic.java
  src/main/java/tagline/logic/LogicManager.java
  src/main/java/tagline/logic/parser/ParserPromptHandlerUtil.java
  src/main/java/tagline/logic/parser/Prompt.java
  src/main/java/tagline/logic/parser/TaglineParser.java
  src/main/java/tagline/logic/parser/contact/AddContactParser.java
  src/main/java/tagline/logic/parser/contact/ContactCommandParser.java
  src/main/java/tagline/logic/parser/contact/DeleteContactParser.java
  src/main/java/tagline/logic/parser/exceptions/PromptRequestException.java
  src/main/java/tagline/logic/parser/note/CreateNoteParser.java
  src/main/java/tagline/logic/parser/note/DeleteNoteParser.java
  src/main/java/tagline/logic/parser/note/NoteCommandParser.java
  src/main/java/tagline/ui/CommandBox.java
  src/main/java/tagline/ui/MainWindow.java
  src/main/java/tagline/ui/PromptHandler.java
  src/main/java/tagline/ui/exceptions/PromptOngoingException.java
  src/main/java/tagline/ui/util/AutoCompleteNode.java
  src/test/java/tagline/logic/parser/CommandParserTestUtil.java
  src/test/java/tagline/logic/parser/ContactCommandParserTest.java
  src/test/java/tagline/logic/parser/note/CreateNoteParserTest.java
  src/test/java/tagline/testutil/LogicStub.java
  src/test/java/tagline/ui/util/AutoCompleteNodeTest.java
Labels: type.Enhancement, type.Story

#151 Dev Guide, User Guide Update and PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/drawioxml/ContactStorageClassDiagram.xml
  docs/diagrams/drawioxml/GroupLogicClassDiagram.xml
  docs/diagrams/drawioxml/GroupModelClassDiagram.xml
  docs/diagrams/drawioxml/GroupStorageClassDiagram.xml
  docs/diagrams/drawioxml/LogicClassDiagram.xml
  docs/diagrams/drawioxml/ModelClassDiagram.xml
  docs/diagrams/drawioxml/NoteModelClassDiagram.xml
  docs/diagrams/drawioxml/NoteStorageClassDiagram.xml
  docs/diagrams/drawioxml/StorageClassDiagram.xml
  docs/images/ContactStorageClassDiagram.png
  docs/images/GroupLogicClassDiagram.png
  docs/images/GroupModelClassDiagram.png
  docs/images/GroupStorageClassDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/NoteModelClassDiagram.png
  docs/images/NoteStorageClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/ug_groupadd1.PNG
  docs/images/ug_groupadd2.PNG
  docs/images/ug_groupcreate1.png
  docs/images/ug_groupcreate2.png
  docs/images/ug_groupdelete1.png
  docs/images/ug_groupdelete2.png
  docs/images/ug_groupfind1.png
  docs/images/ug_groupfind2.png
  docs/images/ug_grouplist1.png
  docs/images/ug_grouplist2.png
  docs/images/ug_grouplist3.png
  docs/images/ug_groupremove1.png
  docs/images/ug_groupremove2.png
  docs/images/ui_notes.png
  docs/team/e0031374.adoc
  src/main/java/tagline/model/util/SampleDataUtil.java
Labels: status.Ongoing
